### ISSUE TITLE
How to create visualization

### ISSUE THREAD

**Issue by akastrin** [jintrone/TEvA#4]
Thank's for sharing this work. I run the machinery executing the command ` java -cp TEvA.jar edu.mit.cci.teva.example.RunSampleCsv' which produced the file `CommunityOutput.Demo.TEvA.xml'. What's next. How should I visualize flow now?

**Comment by jintrone** [comment]
Unfortunately, I've not documented this well, but there are tools for generating a graphml file in the source.  A good starting point is the edu.mit.cci.teva.analysis.AnalysisConsole.  Running this will provide you with a simple text based console, and one of the options is to "create a community graph".  This will generate the graph file.  From there, visualization is up to you, but I used [visone](http://www.visone.info/), and used the ranked layout, with the `window` attribute on each node to lay things out at different levels.  I never did get around to embedding a layout algorithm in the code, but this would be too hard to do.

If anything goes wrong with generating the graphml, let me know and I'll try to fix it.  Visone takes some figuring out, but you can get it to produce some decent visualizations.  For the publication, I postprocessed the images to desaturate the colors.

**Comment by akastrin** [comment]
Thanks for your response. Could you please provide directions how to run `edu.mit.cci.teva.analysis.AnalysisConsole'. I tried with `java -cp TEvA.jar edu.mit.cci.teva.analysis.AnalysisConsole' but the application didn't start.

**Comment by jintrone** [comment]
In Java, you need to implement an abstract class and add a main method to make it runnable.  I've just added a file, `DefaultAnalysisConsole`, in the same package that is runnable.  It should be enough to produce the graph.
